name: trial pipeline
on: push
jobs: 
  notice-to-slack:
    name: notice-to-slack
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "ğŸ“¢ *${{ github.repository }}* ã«æ›´æ–°ãŒã‚ã‚Šã¾ã—ãŸï¼\n
                          ğŸ› ï¸ ãƒ–ãƒ©ãƒ³ãƒ: *${{ github.ref_name }}*\n
                          ğŸ‘¤ ãƒ¦ãƒ¼ã‚¶ãƒ¼: *${{ github.actor }}*\n
                          ğŸ”— [è©³ç´°ã‚’è¦‹ã‚‹](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"


